services:
  # Backend For name change service
  - type: web
    name: farquest-server
    runtime: node
    plan: starter
    previewPlan: starter
    #repo: <your-backend-repo-url> # Replace with your repository URL
    buildCommand: bun i && bun run server:build
    startCommand: bun run start:server
    envVars:
      - fromGroup: farquest-env