import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/admin/sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* <div className='rounded-xl bg-secondary'>filters</div> */}

      <body className={`p-24 flex gap-x-4`}>
        <div className='basis-2/6 h-full'>
          <Sidebar />
        </div>
        <div className='w-full gap-y-4 flex flex-col'>
          <div className='rounded-xl bg-secondary'>filters</div>

          <div className='border border-green-300 h-full w-full rounded-2xl'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
